// GENERATED by scripts/build-fn.mjs from ssr/render.ts — do not edit by hand.

// lib/seo/src/index.ts
var SITE_URL = "https://growitbuddy.com";
var BRAND = {
  name: "GrowitBuddy",
  url: SITE_URL,
  logo: `${SITE_URL}/logo-dark.png`,
  email: "hello@growitbuddy.com",
  twitter: "@growitbuddy",
  description: "GrowitBuddy builds positioning, production, distribution, and inbound demand systems for founders and creators.",
  founder: {
    id: `${SITE_URL}/#suraj-sharma`,
    name: "Suraj Sharma",
    jobTitle: "Founder & CEO"
  },
  /** Social / external profiles — strengthens entity recognition for AI engines (GEO). */
  sameAs: [
    "https://instagram.com/growitbuddy",
    "https://youtube.com/@growitbuddy",
    "https://x.com/growitbuddy",
    "https://www.linkedin.com/company/growitbuddy"
  ]
};
var PAGE_REGISTRY = [
  // Core
  { slug: "home", path: "/", label: "Home", group: "Core", priority: 1, changefreq: "weekly", defaults: { title: "GrowitBuddy - Personal Branding, Content & Distribution Studio", description: "Personal branding, content creation, and video editing for founders, creators, and building their online distribution, Authority & Inbound Leads" } },
  { slug: "about", path: "/about", label: "About", group: "Core", priority: 0.7, changefreq: "monthly", defaults: { title: "About GrowitBuddy", description: "Learn about the GrowitBuddy team, mission, and how we help creators scale." } },
  { slug: "contact", path: "/contact", label: "Contact", group: "Core", priority: 0.7, changefreq: "monthly", defaults: { title: "Contact GrowitBuddy", description: "Get in touch with the GrowitBuddy team." } },
  { slug: "insights", path: "/blog", label: "Insights / Blog", group: "Core", priority: 0.8, changefreq: "weekly", defaults: { title: "GrowitBuddy Insights", description: "Strategies, frameworks, and lessons from running a modern creator agency." } },
  // Services
  { slug: "services", path: "/services", label: "Services", group: "Services", priority: 0.9, changefreq: "monthly", defaults: { title: "Services \u2014 GrowitBuddy", description: "Content, distribution, and growth services for creators and brands." } },
  { slug: "work", path: "/work", label: "Work / Case Studies", group: "Services", priority: 0.8, changefreq: "monthly", defaults: { title: "Our Work \u2014 GrowitBuddy", description: "Real results from the brands and creators we've worked with." } },
  { slug: "framework", path: "/framework", label: "Framework", group: "Services", priority: 0.7, changefreq: "monthly", defaults: { title: "The GrowitBuddy Framework", description: "Our 4-step framework: Positioning, Production, Distribution, Inbound Demand." } },
  { slug: "authority-audit", path: "/authority-audit", label: "Authority Audit", group: "Services", priority: 0.8, changefreq: "monthly", defaults: { title: "Authority Audit \u2014 GrowitBuddy", description: "Free authority audit to identify content and distribution gaps." } },
  // Network & Hiring
  { slug: "influencers", path: "/influencers", label: "Influencers", group: "Network", priority: 0.7, changefreq: "weekly", defaults: { title: "Influencer Network \u2014 GrowitBuddy", description: "Explore our network of vetted creators and influencers." } },
  { slug: "distribution", path: "/distribution", label: "Distribution Network", group: "Network", priority: 0.7, changefreq: "monthly", defaults: { title: "Distribution Network \u2014 GrowitBuddy", description: "Our owned distribution network of pages and creators." } },
  { slug: "links", path: "/links", label: "Links", group: "Utility", priority: 0.5, changefreq: "monthly", defaults: { title: "Links \u2014 GrowitBuddy", description: "All of GrowitBuddy's links in one place." } },
  { slug: "join", path: "/join", label: "Join Network", group: "Network", priority: 0.7, changefreq: "monthly", defaults: { title: "Join the Network \u2014 GrowitBuddy", description: "Join the GrowitBuddy creator and page-owner network." } },
  { slug: "creators", path: "/creators", label: "Creators", group: "Network", priority: 0.7, changefreq: "monthly", defaults: { title: "Creators \u2014 GrowitBuddy", description: "Resources and opportunities for creators with GrowitBuddy." } },
  { slug: "career", path: "/career", label: "Careers (Unified)", group: "Network", priority: 0.7, changefreq: "monthly", defaults: { title: "Careers \u2014 GrowitBuddy", description: "Join GrowitBuddy as a full-time team member, intern, or talent network member." } },
  // Talent Pools
  { slug: "creator-school", path: "/editors-pool", label: "Editors Pool", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Video Editors Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy editors pool. Watch the demo, access resources, and submit your work." } },
  { slug: "video-editors", path: "/video-editors", label: "Video Editors", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Video Editors Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy video editors talent pool." } },
  { slug: "designers-pool", path: "/designers-pool", label: "Designers Pool", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Designers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy designers talent pool." } },
  { slug: "thumbnail-designers", path: "/thumbnail-designers", label: "Thumbnail Designers", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Thumbnail Designers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy thumbnail designers talent pool." } },
  { slug: "writers-pool", path: "/writers-pool", label: "Writers Pool", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Writers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy writers talent pool." } },
  { slug: "social-media-managers", path: "/social-media-managers", label: "Social Media Managers", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Social Media Managers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy social media managers talent pool." } },
  { slug: "motion-designers", path: "/motion-designers", label: "Motion Designers", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Motion Designers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy motion designers talent pool." } },
  { slug: "ai-creators", path: "/ai-creators", label: "AI Creators", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "AI Creators Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy AI creators talent pool." } },
  { slug: "ugc-creators", path: "/ugc-creators", label: "UGC Creators", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "UGC Creators Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy UGC creators talent pool." } },
  { slug: "meme-designers", path: "/meme-designers", label: "Meme Designers", group: "Pools", priority: 0.7, changefreq: "monthly", defaults: { title: "Meme Designers Pool \u2014 GrowitBuddy", description: "Join the GrowitBuddy meme designers talent pool." } },
  // Additional public pages
  { slug: "resources", path: "/resources", label: "Resources", group: "Core", priority: 0.7, changefreq: "weekly", defaults: { title: "Resources \u2014 GrowitBuddy", description: "Free guides, templates, and resources for creators and brands." } },
  { slug: "join-page-owner", path: "/join/page-owner", label: "Join \xB7 Page Owner", group: "Network", priority: 0.6, changefreq: "monthly", defaults: { title: "Join as a Page Owner \u2014 GrowitBuddy", description: "Apply to join the GrowitBuddy distribution network as a page owner." } },
  // Legal — indexed by default (trust signal); admin can flip
  { slug: "privacy", path: "/privacy", label: "Privacy Policy", group: "Legal", priority: 0.3, changefreq: "yearly", defaults: { title: "Privacy Policy \u2014 GrowitBuddy", description: "GrowitBuddy privacy policy and how we handle your data." } },
  { slug: "terms", path: "/terms", label: "Terms of Service", group: "Legal", priority: 0.3, changefreq: "yearly", defaults: { title: "Terms of Service \u2014 GrowitBuddy", description: "GrowitBuddy terms of service." } },
  // Utility — default noindex (not meant for search, excluded from sitemap)
  { slug: "portfolio", path: "/portfolio", label: "Portfolio", group: "Utility", defaults: { title: "Portfolio \u2014 GrowitBuddy", description: "Client portfolio.", index: false, sitemap: false } },
  { slug: "verify", path: "/verify", label: "Verify Certificate", group: "Utility", defaults: { title: "Verify Certificate \u2014 GrowitBuddy", description: "Verify a GrowitBuddy certificate.", index: false, sitemap: false } },
  { slug: "verify-id", path: "/verify/:id", label: "Verify Detail", group: "Utility", defaults: { title: "Certificate Verification \u2014 GrowitBuddy", description: "Verify a specific certificate.", index: false, sitemap: false } }
];
function findEntryByPath(pathname) {
  const exact = PAGE_REGISTRY.find((p) => p.path === pathname);
  if (exact) return exact;
  if (pathname.startsWith("/blog/") || pathname.startsWith("/insights/"))
    return PAGE_REGISTRY.find((p) => p.slug === "insights") ?? null;
  if (/^\/verify\/[^/]+$/.test(pathname)) return PAGE_REGISTRY.find((p) => p.slug === "verify-id") ?? null;
  return null;
}

// artifacts/growitbuddy/ssr/_template.js
var TEMPLATE = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5" />
    <meta name="theme-color" content="#F8F8F6" />
    <meta name="color-scheme" content="light" />

    <title>GrowitBuddy - Personal Branding, Content &amp; Distribution Studio</title>
    <meta name="description" content="Personal branding, content creation, and video editing for founders, creators, and building their online distribution, Authority &amp; Inbound Leads" />
    <meta name="robots" content="index,follow" />
    <meta name="author" content="GrowitBuddy" />

    <meta property="og:type"         content="website" />
    <meta property="og:site_name"    content="GrowitBuddy" />
    <meta property="og:title"        content="GrowitBuddy - Personal Branding, Content &amp; Distribution Studio" />
    <meta property="og:description"  content="Personal branding, content creation, and video editing for founders, creators, and building their online distribution, Authority &amp; Inbound Leads" />
    <meta property="og:url"          content="https://growitbuddy.com/" />
    <meta property="og:image"        content="https://growitbuddy.com/opengraph.jpg" />
    <meta property="og:image:width"  content="1200" />
    <meta property="og:image:height" content="630" />

    <meta name="twitter:card"        content="summary_large_image" />
    <meta name="twitter:site"        content="@growitbuddy" />
    <meta name="twitter:title"       content="GrowitBuddy - Personal Branding, Content &amp; Distribution Studio" />
    <meta name="twitter:description" content="Personal branding, content creation, and video editing for founders, creators, and building their online distribution, Authority &amp; Inbound Leads" />
    <meta name="twitter:image"       content="https://growitbuddy.com/opengraph.jpg" />

    <link rel="canonical" href="https://growitbuddy.com/" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="icon" type="image/png" sizes="32x32"   href="/favicon-32.png" />
    <link rel="icon" type="image/png" sizes="192x192" href="/favicon-192.png" />
    <link rel="icon" type="image/png" sizes="512x512" href="/favicon-512.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

    <!-- Preconnect to reduce font DNS + TLS latency -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

    <!--
      Non-blocking font load:
      rel="preload" as="style" fetches the CSS in the background without blocking render.
      onload switches it to a real stylesheet once fetched.
      The <noscript> fallback covers JS-disabled browsers.
    -->
    <link rel="preload" as="style"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"
      onload="this.onload=null;this.rel='stylesheet'"
    />
    <noscript>
      <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"
      />
    </noscript>

    <link rel="preconnect"   href="https://app.cal.com" />
    <link rel="dns-prefetch" href="https://app.cal.com" />

    <!-- WordPress headless API \u2014 preconnect reduces blog post load latency -->
    <link rel="preconnect"   href="https://blog.growitbuddy.com" crossorigin />
    <link rel="dns-prefetch" href="https://blog.growitbuddy.com" />

    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "Organization",
          "@id": "https://growitbuddy.com/#organization",
          "name": "GrowitBuddy",
          "url": "https://growitbuddy.com",
          "logo": { "@type": "ImageObject", "url": "https://growitbuddy.com/logo-dark.png" },
          "description": "GrowitBuddy builds positioning, production, distribution, and inbound demand systems for founders and creators.",
          "email": "hello@growitbuddy.com",
          "sameAs": [
            "https://instagram.com/growitbuddy",
            "https://youtube.com/@growitbuddy",
            "https://x.com/growitbuddy",
            "https://www.linkedin.com/company/growitbuddy"
          ],
          "contactPoint": {
            "@type": "ContactPoint",
            "email": "hello@growitbuddy.com",
            "contactType": "customer support",
            "availableLanguage": ["en", "hi"]
          },
          "founder": {
            "@type": "Person",
            "@id": "https://growitbuddy.com/#suraj-sharma",
            "name": "Suraj Sharma",
            "jobTitle": "Founder & CEO"
          }
        },
        {
          "@type": "WebSite",
          "@id": "https://growitbuddy.com/#website",
          "url": "https://growitbuddy.com",
          "name": "GrowitBuddy",
          "publisher": { "@id": "https://growitbuddy.com/#organization" }
        }
      ]
    }
    </script>
    <script type="module" crossorigin src="/assets/index-vdExWK2S.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-Bkw1QwSe.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`;

// artifacts/growitbuddy/ssr/render.ts
var API_BASE = process.env.SSR_API_BASE?.replace(/\/$/, "") || "https://growitbuddy-api.onrender.com/api";
var SITE = SITE_URL;
var SITE_NAME = "GrowitBuddy";
var DEFAULT_IMAGE = `${SITE}/opengraph.jpg`;
var TWITTER_HANDLE = "@growitbuddy";
var DATA_TIMEOUT_MS = 2500;
function escAttr(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function safeJson(value) {
  return JSON.stringify(value ?? null).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}
function setTitle(html, title) {
  const tag = `<title>${escAttr(title)}</title>`;
  if (/<title>[\s\S]*?<\/title>/i.test(html))
    return html.replace(/<title>[\s\S]*?<\/title>/i, tag);
  return html.replace(/<\/head>/i, `    ${tag}
  </head>`);
}
function setMeta(html, attr, key, content) {
  const safeKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`<meta\\s+${attr}=["']${safeKey}["'][^>]*>`, "i");
  const tag = `<meta ${attr}="${key}" content="${escAttr(content)}" />`;
  if (re.test(html)) return html.replace(re, tag);
  return html.replace(/<\/head>/i, `    ${tag}
  </head>`);
}
function setCanonical(html, href) {
  const re = /<link\s+rel=["']canonical["'][^>]*>/i;
  const tag = `<link rel="canonical" href="${escAttr(href)}" />`;
  if (re.test(html)) return html.replace(re, tag);
  return html.replace(/<\/head>/i, `    ${tag}
  </head>`);
}
async function fetchJson(url, signal) {
  try {
    const r = await fetch(url, { signal, headers: { accept: "application/json" } });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}
async function loadData(slug, sections) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), DATA_TIMEOUT_MS);
  try {
    const [seoRes, globalRes, ...contentRes] = await Promise.all([
      fetchJson(`${API_BASE}/seo/${encodeURIComponent(slug)}`, ctrl.signal),
      fetchJson(`${API_BASE}/admin/public/content/seo-global`, ctrl.signal),
      ...sections.map(
        (s) => fetchJson(`${API_BASE}/admin/public/content/${encodeURIComponent(s)}`, ctrl.signal)
      )
    ]);
    const seo = seoRes && seoRes.data ? seoRes.data : {};
    const globalIndexable = !(globalRes && globalRes.data && globalRes.data.siteIndexable === false);
    const content = {};
    sections.forEach((s, i) => {
      const d = contentRes[i];
      if (d && d.data && typeof d.data === "object") content[s] = d.data;
    });
    const live = seoRes !== null || globalRes !== null || contentRes.some((d) => d !== null);
    return { seo, globalIndexable, content, live };
  } catch {
    return { seo: {}, globalIndexable: true, content: {}, live: false };
  } finally {
    clearTimeout(timer);
  }
}
function buildHtml(template, entry, pathname, b) {
  const seo = b.seo;
  const title = seo.title ?? entry.defaults.title;
  const description = seo.description ?? entry.defaults.description;
  const indexResolved = b.globalIndexable ? seo.index ?? entry.defaults.index ?? true : false;
  const followResolved = b.globalIndexable ? seo.follow ?? true : false;
  const robots = `${indexResolved ? "index" : "noindex"},${followResolved ? "follow" : "nofollow"}`;
  const canonical = seo.canonical ? seo.canonical.startsWith("http") ? seo.canonical : `${SITE}${seo.canonical}` : `${SITE}${pathname}`;
  const ogImage = seo.ogImage ? seo.ogImage.startsWith("http") ? seo.ogImage : `${SITE}${seo.ogImage}` : DEFAULT_IMAGE;
  const ogTitle = seo.ogTitle ?? title;
  const ogDescription = seo.ogDescription ?? description;
  const twitterImage = seo.twitterImage ? seo.twitterImage.startsWith("http") ? seo.twitterImage : `${SITE}${seo.twitterImage}` : ogImage;
  let html = template;
  html = setTitle(html, title);
  html = setMeta(html, "name", "description", description);
  html = setMeta(html, "name", "robots", robots);
  html = setMeta(html, "property", "og:title", ogTitle);
  html = setMeta(html, "property", "og:description", ogDescription);
  html = setMeta(html, "property", "og:url", canonical);
  html = setMeta(html, "property", "og:type", seo.ogType ?? "website");
  html = setMeta(html, "property", "og:image", ogImage);
  html = setMeta(html, "property", "og:site_name", SITE_NAME);
  html = setMeta(html, "name", "twitter:card", seo.twitterCard ?? "summary_large_image");
  html = setMeta(html, "name", "twitter:title", seo.twitterTitle ?? ogTitle);
  html = setMeta(html, "name", "twitter:description", seo.twitterDescription ?? ogDescription);
  html = setMeta(html, "name", "twitter:image", twitterImage);
  html = setMeta(html, "name", "twitter:site", TWITTER_HANDLE);
  html = setCanonical(html, canonical);
  let schemaScript = "";
  if (seo.schema && seo.schema.trim()) {
    try {
      const parsed = JSON.parse(seo.schema);
      schemaScript = `<script type="application/ld+json" id="gb-jsonld">${safeJson(parsed)}</script>`;
    } catch {
    }
  }
  const bootstrap = `<script>window.__GB_PUBLIC_CONTENT__=${safeJson(b.content)};window.__GB_SEO__=${safeJson({
    slug: entry.slug,
    path: pathname,
    data: seo,
    globalIndexable: b.globalIndexable
  })};</script>`;
  return html.replace(
    /<\/head>/i,
    `    ${bootstrap}
    ${schemaScript}
  </head>`
  );
}
function sendHtml(res, html, cacheControl) {
  res.statusCode = 200;
  res.setHeader("content-type", "text/html; charset=utf-8");
  res.setHeader("cache-control", cacheControl);
  res.end(html);
}
async function handler(req, res) {
  const template = TEMPLATE;
  if (!template) {
    sendHtml(
      res,
      '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex"></head><body><div id="root"></div></body></html>',
      "no-store"
    );
    return;
  }
  try {
    const host = req.headers && req.headers.host || "growitbuddy.com";
    const reqUrl = new URL(req.url || "/", `https://${host}`);
    const pathname = reqUrl.searchParams.get("path") || reqUrl.pathname || "/";
    const entry = findEntryByPath(pathname);
    if (!entry) {
      sendHtml(res, template, "public, s-maxage=30, stale-while-revalidate=300");
      return;
    }
    const sections = Array.from(
      /* @__PURE__ */ new Set([entry.slug, "navbar", "footer", "settings"])
    );
    const bundle = await loadData(entry.slug, sections);
    const html = buildHtml(template, entry, pathname, bundle);
    sendHtml(
      res,
      html,
      bundle.live ? "public, s-maxage=60, stale-while-revalidate=86400" : "public, s-maxage=10, stale-while-revalidate=30"
    );
  } catch {
    sendHtml(res, template, "no-store");
  }
}
export {
  handler as default
};
