// Local-only build helper. Produces api/render.js: a SELF-CONTAINED ESM Vercel
// serverless function bundled from ssr/render.ts with esbuild. Both @workspace/seo
// AND the freshly-built index.html template are INLINED, so Vercel's @vercel/node
// builder has ZERO dependencies to resolve. That is what makes the deploy robust:
// @vercel/node previously failed to build api/render.ts because it imported
// @workspace/seo, whose package "exports" resolves to a .ts source file in
// node_modules (Vite compiles it for the client, but @vercel/node does not).
//
// Run AFTER a client build so dist/public/index.html exists:
//   pnpm --filter @workspace/growitbuddy exec vite build --config vite.config.ts
//   node scripts/build-fn.mjs
//
// The resulting api/render.js is committed and deployed AS-IS; Vercel never runs
// this script. Re-run it whenever ssr/render.ts changes OR the client bundle hash
// changes (so the embedded template points at the current hashed assets).
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { pathToFileURL } from "node:url";
import path from "node:path";

const pkg = path.resolve(import.meta.dirname, "..");
const root = path.resolve(pkg, "..", "..");

// 1) Embed the freshly-built index.html (with hashed asset tags).
const html = readFileSync(path.join(pkg, "dist/public/index.html"), "utf8");
mkdirSync(path.join(pkg, "ssr"), { recursive: true });
writeFileSync(
  path.join(pkg, "ssr/_template.js"),
  `// GENERATED from dist/public/index.html by scripts/build-fn.mjs — do not edit.\nexport const TEMPLATE = ${JSON.stringify(html)};\n`,
);

// 2) Resolve the workspace esbuild (a Vite transitive; not a direct dep here).
const pnpmDir = path.join(root, "node_modules/.pnpm");
const esbDir = readdirSync(pnpmDir).find((d) => d.startsWith("esbuild@"));
if (!esbDir) throw new Error("esbuild not found under node_modules/.pnpm");
const esbuild = await import(
  pathToFileURL(path.join(pnpmDir, esbDir, "node_modules/esbuild/lib/main.js")).href
);

// 3) Bundle ssr/render.ts -> api/render.js. Inline everything; node builtins stay
//    external automatically (platform: node). The result has no bare imports.
await esbuild.build({
  entryPoints: [path.join(pkg, "ssr/render.ts")],
  outfile: path.join(pkg, "api/render.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  banner: {
    js: "// GENERATED by scripts/build-fn.mjs from ssr/render.ts — do not edit by hand.",
  },
});

// 4) Sanity output.
const out = readFileSync(path.join(pkg, "api/render.js"), "utf8");
const asset = (html.match(/assets\/index-[A-Za-z0-9_-]+\.js/) || ["?"])[0];
console.log(`api/render.js: ${out.length} bytes`);
console.log(`embedded asset: ${asset}`);
console.log(`seo inlined (no @workspace import): ${!out.includes('from "@workspace/seo"')}`);
console.log(`template inlined (no ./_template import): ${!out.includes('"./_template')}`);
console.log(`has registry lookup: ${out.includes("findEntryByPath") || out.includes("PAGE_REGISTRY")}`);
