// Local-only build helper. Produces api/render.js: a near-self-contained ESM
// Vercel serverless function bundled from ssr/render.ts with esbuild. @workspace/seo
// is INLINED — that is the fix, because @vercel/node cannot build a function that
// imports @workspace/seo (its package "exports" resolves to a .ts source file in
// node_modules; Vite compiles it for the client, but @vercel/node does not).
//
// The HTML template is the ONLY external dependency: api/render.js imports
// ./_template.js, which scripts/postbuild-ssr.mjs regenerates from EACH build's
// dist/public/index.html. This keeps the SSR shell's hashed-asset references in
// lockstep with whatever assets the build produced (local OR Vercel), avoiding the
// hash drift that a baked-in template causes.
//
// Run AFTER a client build + postbuild so api/_template.js exists for local tests:
//   pnpm --filter @workspace/growitbuddy exec vite build --config vite.config.ts
//   node scripts/postbuild-ssr.mjs
//   node scripts/build-fn.mjs
//
// api/render.js is committed and deployed AS-IS; Vercel never runs this script.
// Re-run it only when ssr/render.ts changes.
import { readFileSync, readdirSync } from "node:fs";
import { pathToFileURL } from "node:url";
import path from "node:path";

const pkg = path.resolve(import.meta.dirname, "..");
const root = path.resolve(pkg, "..", "..");

// Resolve the workspace esbuild (a Vite transitive; not a direct dep here).
const pnpmDir = path.join(root, "node_modules/.pnpm");
const esbDir = readdirSync(pnpmDir).find((d) => d.startsWith("esbuild@"));
if (!esbDir) throw new Error("esbuild not found under node_modules/.pnpm");
const esbuild = await import(
  pathToFileURL(path.join(pnpmDir, esbDir, "node_modules/esbuild/lib/main.js")).href
);

// Bundle ssr/render.ts -> api/render.js. Inline @workspace/seo; keep ./_template.js
// external (resolved at runtime to the build-generated sibling api/_template.js).
await esbuild.build({
  entryPoints: [path.join(pkg, "ssr/render.ts")],
  outfile: path.join(pkg, "api/render.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  external: ["./_template.js"],
  banner: {
    js: "// GENERATED by scripts/build-fn.mjs from ssr/render.ts — do not edit by hand.",
  },
});

const out = readFileSync(path.join(pkg, "api/render.js"), "utf8");
console.log(`api/render.js: ${out.length} bytes`);
console.log(`seo inlined (no @workspace import): ${!out.includes('from "@workspace/seo"')}`);
console.log(`template kept external: ${out.includes('from "./_template.js"')}`);
console.log(`has registry lookup: ${out.includes("findEntryByPath") || out.includes("PAGE_REGISTRY")}`);
