/**
 * Postbuild step for the Vercel SSR renderer (api/render.ts).
 *
 * Vite builds the SPA into dist/public (index.html + hashed assets). The
 * serverless renderer needs that BUILT index.html (with the correct hashed
 * <script>/<link> tags) as its template. Rather than ship the file separately
 * and read it from disk at runtime (which on Vercel needs functions.includeFiles
 * and is fragile), we EMBED it into a generated module, api/_template.js, that
 * the function imports. esbuild bundles the string straight into the function —
 * no filesystem reads, no includeFiles, no path/cwd guesswork. Files in /api
 * whose names start with "_" are private (Vercel does NOT turn them into
 * endpoints), so _template.js is import-only.
 *
 * Two modes:
 *   (default / copy-only)  Generate the template module, KEEP dist/public/index.html.
 *                          Vercel keeps serving the static shell via the SPA
 *                          rewrite — routing is unchanged. Used in Phase 1 so
 *                          the function can be deployed + verified at /api/render
 *                          with ZERO risk to the live site.
 *   (--activate)           Generate the module AND remove dist/public/index.html.
 *                          With index.html gone from the output root, the SPA
 *                          routes fall through the rewrite to the function and
 *                          all HTML is server-rendered. Static assets are
 *                          unaffected (Vercel serves real files first).
 *
 * Never edits index.html or _template.js by hand — re-run the build instead.
 */
import { existsSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const publicHtml = resolve(root, "dist/public/index.html");
const apiTemplate = resolve(root, "api/_template.js");

const activate = process.argv.includes("--activate");

if (!existsSync(publicHtml)) {
  console.error(`[postbuild-ssr] ERROR: ${publicHtml} not found. Did 'vite build' run first?`);
  process.exit(1);
}

const html = readFileSync(publicHtml, "utf8");
const moduleSource =
  `// AUTO-GENERATED by scripts/postbuild-ssr.mjs during build. Do not edit or commit.\n` +
  `export const TEMPLATE = ${JSON.stringify(html)};\n`;
writeFileSync(apiTemplate, moduleSource, "utf8");
console.log(`[postbuild-ssr] wrote embedded template -> ${apiTemplate} (${html.length} bytes)`);

if (activate) {
  rmSync(publicHtml, { force: true });
  console.log(
    `[postbuild-ssr] ACTIVATE: removed ${publicHtml} — all HTML routes now render via api/render`,
  );
} else {
  console.log(
    `[postbuild-ssr] copy-only: kept ${publicHtml} — routing unchanged (Phase 1)`,
  );
}
